image:
  repository: 297165773875.dkr.ecr.ap-northeast-2.amazonaws.com/petflow/order-service
  tag: "b2de90bc12df4dbd2f0f9ad15028a2120b9ad1f8" # TODO: CI가 커밋 SHA 등 실제 빌드 태그를 넣도록 바뀌면 그걸로 교체
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    memory: 512Mi
env:
  - name: SPRING_PROFILES_ACTIVE
    value: "dev"
  - name: SPRING_DATASOURCE_URL
    valueFrom:
      secretKeyRef:
        name: db-credentials
        key: SPRING_DATASOURCE_URL
  - name: SPRING_DATASOURCE_USERNAME
    valueFrom:
      secretKeyRef:
        name: db-credentials
        key: SPRING_DATASOURCE_USERNAME
  - name: SPRING_DATASOURCE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: db-credentials
        key: SPRING_DATASOURCE_PASSWORD
  - name: INTERNAL_GATEWAY_SECRET
    valueFrom:
      secretKeyRef:
        name: gateway-secret
        key: INTERNAL_GATEWAY_SECRET
